sudo: required
language: node_js
node_js: node
cache: yarn
services: docker
group: deprecated-2017Q4

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - docker-compose -f docker-compose-tests.yml build test-ci
  - docker-compose -f docker-compose-tests.yml run test-ci

after_success: bash ./scripts/deploy.sh

after_script:
  - greenkeeper-lockfile-upload
  - docker-compose -f docker-compose-tests.yml down -v
