version: '2.1'

services:

  tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-watch
    volumes:
      - elasticsearch-updater-tests-node_modules:/code/node_modules
    environment:
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
    links:
    - elasticsearch:es


  travis-tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run travis
    user: root
    volumes:
      - elasticsearch-updater-tests-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
    - elasticsearch:es

  elasticsearch:
    image: "nhsuk/profiles-db-elastic:${profiles_db_elastic_docker_image_tag-0.4.0}"
    ports:
      - 9200:9200 

volumes:
  elasticsearch-updater-tests-node_modules:
