version: '2.1'

services:

  base-app:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}
      JSON_FILE_URL: https://nhsukgpdataetl.blob.core.windows.net/etl-output/gp-data-merged.json
      ES_HOST: es
      ES_INDEX: profiles

  elasticsearch-updater:
    extends:
      service: base-app
    volumes:
      - elasticsearch-updater-node_modules:/code/node_modules
    links:
    - elasticsearch:es

  elasticsearch:
    image: "nhsuk/profiles-db-elastic:${profiles_db_elastic_docker_image_tag-0.4.0}"
    ports:
      - 9200:9200 

volumes:
  elasticsearch-updater-node_modules:
