version: '2.1'

services:

  base-app:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}
      JSON_FILE_URL: https://nhsukgpdataetl.blob.core.windows.net/etl-output/gp-data-merged.json
      ES_HOST: es
      ES_INDEX: profiles
      CHANGE_THRESHOLD: '0.96'

  elasticsearch-updater-profiles:
    extends:
      service: base-app
    volumes:
      - elasticsearch-updater-profiles-node_modules:/code/node_modules
    environment:
      JSON_FILE_URL: https://nhsukgpdataetl.blob.core.windows.net/etl-output/gp-data-merged.json
      ES_INDEX: profiles
    links:
    - elasticsearch:es

  elasticsearch-updater-pharmacies:
    extends:
      service: base-app
    volumes:
      - elasticsearch-updater-pharmacies-node_modules:/code/node_modules
    environment:
      JSON_FILE_URL: https://nhsukpharmacydataetl.blob.core.windows.net/etl-output/pharmacy-data.json
      ES_INDEX: pharmacies
    links:
    - elasticsearch:es

  elasticsearch-updater-sexual-health-services:
    extends:
      service: base-app
    volumes:
      - elasticsearch-updater-sexual-health-services-node_modules:/code/node_modules
    environment:
      JSON_FILE_URL: https://primarycare.blob.core.windows.net/etl-output/sexual-health-service-data-merged.json
      ES_INDEX: sexual-health-services
    links:
    - elasticsearch:es

  elasticsearch:
    image: "nhsuk/profiles-db-elastic:${profiles_db_elastic_docker_image_tag-0.4.0}"
    ports:
      - 9200:9200

volumes:
  elasticsearch-updater-profiles-node_modules:
  elasticsearch-updater-pharmacies-node_modules:
  elasticsearch-updater-sexual-health-services-node_modules:
