version: '2'
services:

  elasticsearch-updater-profiles:
    image: nhsuk/elasticsearch-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
      JSON_FILE_URL: ${JSON_FILE_URL}
      ES_HOST: profiles-db-elastic.profiles-db-elastic
      ES_INDEX: profiles
      CHANGE_THRESHOLD: ${CHANGE_THRESHOLD}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE}
    labels:
      io.rancher.container.pull_image: always
