version: '2'
services:

  elasticsearch-updater-profiles:
    image: nhsuk/elasticsearch-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: production
      JSON_FILE_URL: ${JSON_FILE_URL_PROFILES}
      ES_HOST: ${ES_HOST_PROFILES}
      ES_REPLICAS: ${ES_REPLICAS_PROFILES}
      ES_SHARDS: ${ES_SHARDS_PROFILES}
      ES_WATCHER_PREFIX: ${ES_WATCHER_PREFIX_PROFILES}
      ES_MONITOR_PREFIX: ${ES_MONITOR_PREFIX_PROFILES}
      ES_INDEX: profiles
      ES_TIMEOUT_SECONDS: ${ES_TIMEOUT_SECONDS_PROFILES}
      CHANGE_THRESHOLD: ${CHANGE_THRESHOLD_PROFILES}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE_PROFILES}
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: elasticsearch-updater-profiles
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json

  elasticsearch-updater-pharmacies:
    image: nhsuk/elasticsearch-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: production
      JSON_FILE_URL: ${JSON_FILE_URL_PHARMACIES}
      ES_HOST: ${ES_HOST_PHARMACIES}
      ES_REPLICAS: ${ES_REPLICAS_PHARMACIES}
      ES_SHARDS: ${ES_SHARDS_PHARMACIES}
      ES_WATCHER_PREFIX: ${ES_WATCHER_PREFIX_PHARMACIES}
      ES_MONITOR_PREFIX: ${ES_MONITOR_PREFIX_PHARMACIES}
      ES_INDEX: pharmacies
      ES_TIMEOUT_SECONDS: ${ES_TIMEOUT_SECONDS_PHARMACIES}
      CHANGE_THRESHOLD: ${CHANGE_THRESHOLD_PHARMACIES}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE_PHARMACIES}
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: elasticsearch-updater-pharmacy
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json

  elasticsearch-updater-sexual-health-services:
    image: nhsuk/elasticsearch-updater:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: production
      JSON_FILE_URL: ${JSON_FILE_URL_SEXUAL_HEALTH_SERVICES}
      ES_HOST: ${ES_HOST_SEXUAL_HEALTH_SERVICES}
      ES_REPLICAS: ${ES_REPLICAS_SEXUAL_HEALTH_SERVICES}
      ES_SHARDS: ${ES_SHARDS_SEXUAL_HEALTH_SERVICES}
      ES_WATCHER_PREFIX: ${ES_WATCHER_PREFIX_SEXUAL_HEALTH_SERVICES}
      ES_MONITOR_PREFIX: ${ES_MONITOR_PREFIX_SEXUAL_HEALTH_SERVICES}
      ES_INDEX: sexual-health-services
      ES_TIMEOUT_SECONDS: ${ES_TIMEOUT_SECONDS_SEXUAL_HEALTH_SERVICES}
      CHANGE_THRESHOLD: ${CHANGE_THRESHOLD_SEXUAL_HEALTH_SERVICES}
      UPDATE_SCHEDULE: ${UPDATE_SCHEDULE_SEXUAL_HEALTH_SERVICES}
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: elasticsearch-updater-sexual-health-services
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
