#!/bin/bash
docker-compose down -v
docker-compose up --build --force-recreate elasticsearch elasticsearch-updater-profiles elasticsearch-updater-pharmacies elasticsearch-updater-sexual-health-services
